
const https  = require("https");
const fs     = require("fs");
const path   = require("path");
const url    = require("url");

// ── TLS config — use the certs generated by the setup script ────────────────
const TLS_OPTIONS = {
  key:  fs.readFileSync(path.join(__dirname, "server.key")),
  cert: fs.readFileSync(path.join(__dirname, "server.crt")),
};

// ── Constants ────────────────────────────────────────────────────────────────
const PORT     = 443;
const START    = "2024-01-01T00:00:00Z";
const EXPIRE   = "2099-12-31T23:59:59Z";
const PRODUCTS = [
  "com.locket.premium.yearly",
  "com.locket.premium.monthly",
  "Gold",
  "gold",
  "pro",
  "premium",
];

// ── Response builders ────────────────────────────────────────────────────────
function makeSubscription() {
  return {
    is_sandbox:                  false,
    ownership_type:              "PURCHASED",
    period_type:                 "normal",
    purchase_date:               START,
    original_purchase_date:      START,
    expires_date:                EXPIRE,
    latest_expires_date:         EXPIRE,
    store:                       "app_store",
    grace_period_expires_date:   null,
    unsubscribe_detected_at:     null,
    billing_issues_detected_at:  null,
    refund_at:                   null,
    is_trial_period:             false,
  };
}

function makeEntitlement(pid) {
  return {
    ...makeSubscription(),
    product_identifier: pid,
    identifier:         pid,
    active:             true,
    is_active:          true,
    renewal_state:      "subscribed",
    will_renew:         true,
  };
}

function buildSubscriberBody(userId) {
  const subs = {}, ents = {};
  PRODUCTS.forEach(p => { subs[p] = makeSubscription(); ents[p] = makeEntitlement(p); });
  return {
    request_date:    new Date().toISOString(),
    request_date_ms: Date.now(),
    subscriber: {
      original_app_user_id:                  userId || "anonymous",
      original_application_version:          "1.0",
      original_purchase_date:                START,
      first_seen:                            START,
      last_seen:                             new Date().toISOString(),
      management_url:                        null,
      subscriptions:                         subs,
      entitlements:                          ents,
      non_subscriptions:                     {},
      other_purchases:                       {},
      active_subscriptions:                  PRODUCTS,
      all_purchased_product_identifiers:     PRODUCTS,
      all_expiration_dates_by_product:       Object.fromEntries(PRODUCTS.map(p => [p, EXPIRE])),
      all_purchased_dates_by_product:        Object.fromEntries(PRODUCTS.map(p => [p, START])),
    }
  };
}

function buildOfferingsBody() {
  return {
    current_offering_id: "gold",
    offerings: [{
      identifier:  "gold",
      description: "Locket Gold",
      metadata:    {},
      packages: PRODUCTS.map(pid => ({
        identifier:                  "$rc_annual",
        platform_product_identifier: pid,
        product: {
          identifier:    pid,
          title:         "Locket Gold",
          description:   "Locket Gold Annual",
          price:         0.00,
          price_string:  "$0.00",
          currency_code: "USD",
          intro_price:   null,
        }
      }))
    }]
  };
}

// ── CORS + cache headers ─────────────────────────────────────────────────────
const BASE_HEADERS = {
  "Access-Control-Allow-Origin":  "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "*",
  "Content-Type":                 "application/json",
  "Cache-Control":                "public, max-age=315360000, immutable",
  "Expires":                      "Fri, 31 Dec 2099 23:59:59 GMT",
};

function send(res, statusCode, body) {
  const payload = JSON.stringify(body);
  res.writeHead(statusCode, { ...BASE_HEADERS, "Content-Length": Buffer.byteLength(payload) });
  res.end(payload);
}

// ── Read request body ────────────────────────────────────────────────────────
function readBody(req) {
  return new Promise((resolve) => {
    let data = "";
    req.on("data", chunk => { data += chunk; });
    req.on("end", () => {
      try { resolve(JSON.parse(data)); } catch { resolve({}); }
    });
  });
}

// ── Request handler ──────────────────────────────────────────────────────────
async function handler(req, res) {
  const { pathname } = url.parse(req.url);
  console.log(`[${new Date().toISOString()}] ${req.method} ${pathname}`);

  // Preflight
  if (req.method === "OPTIONS") {
    res.writeHead(204, BASE_HEADERS);
    res.end();
    return;
  }

  // /v1/subscribers/:userId  OR  /v2/subscribers/:userId
  const subMatch = pathname.match(/\/v[12]\/subscribers\/([^/?]+)/);
  if (subMatch) {
    const userId = decodeURIComponent(subMatch[1]);
    return send(res, 200, buildSubscriberBody(userId));
  }

  // /v1/receipts
  if (pathname.endsWith("/receipts")) {
    const body   = await readBody(req);
    const userId = body.app_user_id || "anonymous";
    return send(res, 200, buildSubscriberBody(userId));
  }

  // /v1/offerings
  if (pathname.endsWith("/offerings")) {
    return send(res, 200, buildOfferingsBody());
  }

  // Catch-all — return Gold for any unmatched RC endpoint
  return send(res, 200, buildSubscriberBody("anonymous"));
}

// ── Start server ─────────────────────────────────────────────────────────────
https.createServer(TLS_OPTIONS, handler).listen(PORT, "0.0.0.0", () => {
  console.log(`Fake RC API listening on :${PORT}`);
  console.log(`Serving Gold for all api.revenuecat.com requests`);
});
